version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      day: monday
      time: '04:00'
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 1
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      day: monday
      time: '04:00'
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - '*'
