CREATE TABLE `schedule_events` (
  `id` CHAR(36) NOT NULL,
  `group_id` CHAR(36) NOT NULL,
  `schedule_period_id` CHAR(36) NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `event_status` VARCHAR(32) NOT NULL,
  `object_type` VARCHAR(64) NOT NULL,
  `object_id` CHAR(36) NULL,
  `operation_id` CHAR(36) NOT NULL,
  `parent_event_id` CHAR(36) NULL,
  `initiated_by_user_id` CHAR(36) NULL,
  `operator_user_id` CHAR(36) NULL,
  `approver_user_id` CHAR(36) NULL,
  `reason` VARCHAR(1000) NULL,
  `before_data` JSON NULL,
  `after_data` JSON NULL,
  `affected_membership_ids` JSON NOT NULL,
  `affected_shift_ids` JSON NOT NULL,
  `statistics_delta` JSON NULL,
  `occurred_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `schedule_events_group_occurred_idx` (`group_id`, `occurred_at`, `id`),
  KEY `schedule_events_group_type_occurred_idx` (`group_id`, `event_type`, `occurred_at`, `id`),
  KEY `schedule_events_period_occurred_idx` (`schedule_period_id`, `occurred_at`, `id`),
  KEY `schedule_events_operation_idx` (`operation_id`),
  KEY `schedule_events_parent_event_idx` (`parent_event_id`),
  CONSTRAINT `schedule_events_group_id_fk` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`),
  CONSTRAINT `schedule_events_initiated_by_user_id_fk` FOREIGN KEY (`initiated_by_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `schedule_events_operator_user_id_fk` FOREIGN KEY (`operator_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `schedule_events_approver_user_id_fk` FOREIGN KEY (`approver_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `audit_logs` (
  `id` CHAR(36) NOT NULL,
  `group_id` CHAR(36) NULL,
  `actor_user_id` CHAR(36) NULL,
  `action` VARCHAR(64) NOT NULL,
  `outcome` VARCHAR(32) NOT NULL,
  `target_type` VARCHAR(64) NULL,
  `target_id` CHAR(36) NULL,
  `operation_id` CHAR(36) NOT NULL,
  `request_id` CHAR(36) NULL,
  `metadata` JSON NOT NULL,
  `occurred_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `audit_logs_group_occurred_idx` (`group_id`, `occurred_at`, `id`),
  KEY `audit_logs_actor_occurred_idx` (`actor_user_id`, `occurred_at`, `id`),
  KEY `audit_logs_action_occurred_idx` (`action`, `occurred_at`, `id`),
  KEY `audit_logs_operation_idx` (`operation_id`),
  CONSTRAINT `audit_logs_group_id_fk` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`),
  CONSTRAINT `audit_logs_actor_user_id_fk` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
