CREATE TABLE `directory_campuses` (
  `id` CHAR(36) NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `display_order` INT UNSIGNED NOT NULL,
  `dialing_note` VARCHAR(1000) NULL,
  `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `directory_campuses_code_unique` (`code`),
  KEY `directory_campuses_display_order_idx` (`display_order`, `code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `directory_import_batches` (
  `id` CHAR(36) NOT NULL,
  `import_version` VARCHAR(64) NOT NULL,
  `schema_version` INT UNSIGNED NOT NULL,
  `status` ENUM('draft', 'published', 'superseded', 'failed') NOT NULL DEFAULT 'draft',
  `effective_on` DATE NOT NULL,
  `manifest_sha256` CHAR(64) NOT NULL,
  `source_document_count` INT UNSIGNED NOT NULL,
  `entry_count` INT UNSIGNED NOT NULL,
  `contact_method_count` INT UNSIGNED NOT NULL,
  `warning_count` INT UNSIGNED NOT NULL,
  `diff_summary` JSON NOT NULL,
  `warning_summary` JSON NOT NULL,
  `published_at` TIMESTAMP(3) NULL,
  `superseded_at` TIMESTAMP(3) NULL,
  `published_slot` TINYINT UNSIGNED GENERATED ALWAYS AS (
    IF(`status` = 'published', 1, NULL)
  ) STORED,
  `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `directory_import_batches_version_unique` (`import_version`),
  UNIQUE KEY `directory_import_batches_manifest_unique` (`manifest_sha256`),
  UNIQUE KEY `directory_import_batches_published_slot_unique` (`published_slot`),
  KEY `directory_import_batches_effective_status_idx` (`effective_on`, `status`),
  CONSTRAINT `directory_import_batches_schema_version_check` CHECK (`schema_version` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `directory_source_documents` (
  `id` CHAR(36) NOT NULL,
  `batch_id` CHAR(36) NOT NULL,
  `campus_id` CHAR(36) NOT NULL,
  `document_key` VARCHAR(128) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `source_sha256` CHAR(64) NOT NULL,
  `effective_on` DATE NOT NULL,
  `page_count` INT UNSIGNED NOT NULL,
  `display_order` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `directory_source_documents_batch_key_unique` (`batch_id`, `document_key`),
  UNIQUE KEY `directory_source_documents_batch_hash_unique` (`batch_id`, `source_sha256`),
  KEY `directory_source_documents_batch_campus_idx` (`batch_id`, `campus_id`, `display_order`),
  CONSTRAINT `directory_source_documents_batch_id_fk` FOREIGN KEY (`batch_id`) REFERENCES `directory_import_batches` (`id`),
  CONSTRAINT `directory_source_documents_campus_id_fk` FOREIGN KEY (`campus_id`) REFERENCES `directory_campuses` (`id`),
  CONSTRAINT `directory_source_documents_page_count_check` CHECK (`page_count` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `directory_entries` (
  `id` CHAR(36) NOT NULL,
  `batch_id` CHAR(36) NOT NULL,
  `source_document_id` CHAR(36) NOT NULL,
  `campus_id` CHAR(36) NOT NULL,
  `entry_key` VARCHAR(191) NOT NULL,
  `source_page` INT UNSIGNED NOT NULL,
  `source_locator` VARCHAR(191) NOT NULL,
  `section_name` VARCHAR(100) NULL,
  `department_name` VARCHAR(150) NULL,
  `subunit_name` VARCHAR(150) NULL,
  `contact_name` VARCHAR(150) NULL,
  `building_name` VARCHAR(100) NULL,
  `floor_name` VARCHAR(64) NULL,
  `room_name` VARCHAR(100) NULL,
  `entry_kind` ENUM('department', 'person', 'service', 'facility', 'vendor', 'emergency', 'switchboard', 'other') NOT NULL,
  `notes` VARCHAR(1000) NULL,
  `visibility` ENUM('member', 'administrator') NOT NULL DEFAULT 'member',
  `verification_status` ENUM('source_exact', 'needs_review', 'manually_verified') NOT NULL DEFAULT 'source_exact',
  `display_order` INT UNSIGNED NOT NULL,
  `search_text` TEXT NOT NULL,
  `content_sha256` CHAR(64) NOT NULL,
  `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `directory_entries_batch_key_unique` (`batch_id`, `entry_key`),
  UNIQUE KEY `directory_entries_batch_source_unique` (`batch_id`, `source_document_id`, `source_locator`),
  KEY `directory_entries_batch_campus_order_idx` (`batch_id`, `campus_id`, `display_order`),
  KEY `directory_entries_batch_department_idx` (`batch_id`, `department_name`, `subunit_name`),
  KEY `directory_entries_batch_kind_idx` (`batch_id`, `entry_kind`),
  KEY `directory_entries_source_page_idx` (`source_document_id`, `source_page`, `display_order`),
  FULLTEXT KEY `directory_entries_search_fulltext` (`search_text`) WITH PARSER ngram,
  CONSTRAINT `directory_entries_batch_id_fk` FOREIGN KEY (`batch_id`) REFERENCES `directory_import_batches` (`id`),
  CONSTRAINT `directory_entries_source_document_id_fk` FOREIGN KEY (`source_document_id`) REFERENCES `directory_source_documents` (`id`),
  CONSTRAINT `directory_entries_campus_id_fk` FOREIGN KEY (`campus_id`) REFERENCES `directory_campuses` (`id`),
  CONSTRAINT `directory_entries_source_page_check` CHECK (`source_page` > 0),
  CONSTRAINT `directory_entries_name_check` CHECK (`department_name` IS NOT NULL OR `contact_name` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `directory_contact_methods` (
  `id` CHAR(36) NOT NULL,
  `entry_id` CHAR(36) NOT NULL,
  `type` ENUM('voice', 'mobile', 'fax', 'emergency', 'hotline', 'other') NOT NULL DEFAULT 'voice',
  `label` VARCHAR(100) NULL,
  `full_number` VARCHAR(64) NULL,
  `internal_extension` VARCHAR(32) NULL,
  `normalized_full_number` VARCHAR(32) NULL,
  `normalized_internal_extension` VARCHAR(20) NULL,
  `contact_sha256` CHAR(64) NOT NULL,
  `is_primary` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `display_order` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `directory_contact_methods_entry_hash_unique` (`entry_id`, `contact_sha256`),
  KEY `directory_contact_methods_entry_order_idx` (`entry_id`, `display_order`),
  KEY `directory_contact_methods_full_number_idx` (`normalized_full_number`),
  KEY `directory_contact_methods_extension_idx` (`normalized_internal_extension`),
  CONSTRAINT `directory_contact_methods_entry_id_fk` FOREIGN KEY (`entry_id`) REFERENCES `directory_entries` (`id`),
  CONSTRAINT `directory_contact_methods_value_check` CHECK (`normalized_full_number` IS NOT NULL OR `normalized_internal_extension` IS NOT NULL),
  CONSTRAINT `directory_contact_methods_primary_check` CHECK (`is_primary` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--> statement-breakpoint
CREATE TABLE `directory_search_aliases` (
  `id` CHAR(36) NOT NULL,
  `entry_id` CHAR(36) NOT NULL,
  `type` ENUM('source', 'manual', 'pinyin_full', 'pinyin_compact', 'pinyin_initials') NOT NULL,
  `alias_value` VARCHAR(255) NOT NULL,
  `normalized_value` VARCHAR(255) NOT NULL,
  `alias_sha256` CHAR(64) NOT NULL,
  `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `directory_search_aliases_entry_hash_unique` (`entry_id`, `alias_sha256`),
  KEY `directory_search_aliases_normalized_idx` (`normalized_value`, `type`),
  KEY `directory_search_aliases_entry_type_idx` (`entry_id`, `type`),
  CONSTRAINT `directory_search_aliases_entry_id_fk` FOREIGN KEY (`entry_id`) REFERENCES `directory_entries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
