import type { IconColorRole, IconContextKey } from './types.js';

export type { IconContextKey } from './types.js';

export interface IconContextSpec {
  readonly activeColorRole: IconColorRole;
  readonly containerHeightPx: number;
  readonly inactiveColorRole: IconColorRole;
  readonly key: IconContextKey;
  readonly opticalOffset: readonly [number, number];
  readonly sizePx: number;
  readonly strokeWidth: number;
  readonly transformOrigin: string;
  readonly containerWidthPx: number;
}

export const iconContextSpecs = {
  'mobile-bottom-navigation': {
    key: 'mobile-bottom-navigation',
    sizePx: 23,
    strokeWidth: 2,
    containerWidthPx: 23,
    containerHeightPx: 23,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'secondary',
  },
  'desktop-navigation': {
    key: 'desktop-navigation',
    sizePx: 20,
    strokeWidth: 2,
    containerWidthPx: 20,
    containerHeightPx: 20,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'secondary',
  },
  'top-profile': {
    key: 'top-profile',
    sizePx: 20,
    strokeWidth: 2,
    containerWidthPx: 20,
    containerHeightPx: 20,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'primary',
  },
  'top-bell': {
    key: 'top-bell',
    sizePx: 21.6,
    strokeWidth: 1.8,
    containerWidthPx: 21.6,
    containerHeightPx: 21.6,
    opticalOffset: [0, 0],
    transformOrigin: '12px 3px',
    activeColorRole: 'primary',
    inactiveColorRole: 'primary',
  },
  'directory-mode': {
    key: 'directory-mode',
    sizePx: 18,
    strokeWidth: 1.8,
    containerWidthPx: 18,
    containerHeightPx: 18,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'directoryModeInactive',
  },
  'directory-favorite': {
    key: 'directory-favorite',
    sizePx: 21,
    strokeWidth: 2,
    containerWidthPx: 21,
    containerHeightPx: 21,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'favorite',
    inactiveColorRole: 'muted',
  },
  'directory-phone': {
    key: 'directory-phone',
    sizePx: 17,
    strokeWidth: 2,
    containerWidthPx: 17,
    containerHeightPx: 17,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'primary',
  },
  'calendar-filter': {
    key: 'calendar-filter',
    sizePx: 20,
    strokeWidth: 1.8,
    containerWidthPx: 20,
    containerHeightPx: 20,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'primary',
  },
  'calendar-locate': {
    key: 'calendar-locate',
    sizePx: 16,
    strokeWidth: 2,
    containerWidthPx: 16,
    containerHeightPx: 16,
    opticalOffset: [0, 0],
    transformOrigin: '12px 12px',
    activeColorRole: 'primary',
    inactiveColorRole: 'primary',
  },
  'more-row': {
    key: 'more-row',
    sizePx: 20,
    strokeWidth: 2,
    containerWidthPx: 20,
    containerHeightPx: 20,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'secondary',
  },
  'calendar-phone-small': {
    key: 'calendar-phone-small',
    sizePx: 16,
    strokeWidth: 2,
    containerWidthPx: 16,
    containerHeightPx: 16,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'primary',
  },
  'duty-phone': {
    key: 'duty-phone',
    sizePx: 18,
    strokeWidth: 2,
    containerWidthPx: 18,
    containerHeightPx: 18,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'primary',
  },
  'static-action': {
    key: 'static-action',
    sizePx: 20,
    strokeWidth: 2,
    containerWidthPx: 20,
    containerHeightPx: 20,
    opticalOffset: [0, 0],
    transformOrigin: 'center',
    activeColorRole: 'primary',
    inactiveColorRole: 'secondary',
  },
} as const satisfies Readonly<Record<IconContextKey, IconContextSpec>>;
