export const calendarGoldenMonths = ['2026-08', '2026-09', '2026-10', '2028-02'] as const;

export interface CalendarGoldenHoliday {
  readonly date: string;
  readonly holidayName: string;
  readonly isOffDay: boolean;
  readonly isWorkday: boolean;
}

export const calendarGoldenAssignments = [
  {
    businessDate: '2026-08-01',
    changeMarkers: [],
    endsAt: '2026-08-01T08:00:00.000Z',
    id: 'assignment-a',
    plannedMemberName: '张医生',
    plannedMembershipId: 'member-planned',
    schedulePeriodId: 'period-a',
    scheduleRoleId: 'role-a',
    scheduleRoleName: '一线',
    shiftTypeAbbreviation: 'A',
    shiftTypeColor: '#DCEEFF',
    shiftTypeId: 'shift-a',
    shiftTypeName: '白班',
    shiftTypeTextColor: '#084FA6',
    slotPosition: 1,
    startsAt: '2026-08-01T00:00:00.000Z',
  },
  {
    actualMemberName: '李医生',
    actualMembershipId: 'member-actual',
    businessDate: '2026-08-01',
    changeMarkers: ['swap'],
    endsAt: '2026-08-02T00:00:00.000Z',
    id: 'assignment-p',
    plannedMemberName: '王医生',
    plannedMembershipId: 'member-planned-2',
    schedulePeriodId: 'period-b',
    scheduleRoleId: 'role-b',
    scheduleRoleName: '二线',
    shiftTypeAbbreviation: 'P',
    shiftTypeColor: '#EAF8EF',
    shiftTypeId: 'shift-p',
    shiftTypeName: '夜班',
    shiftTypeTextColor: '#17672C',
    slotPosition: 1,
    startsAt: '2026-08-01T10:00:00.000Z',
  },
  {
    businessDate: '2026-08-01',
    changeMarkers: ['leave-cover'],
    endsAt: '2026-08-02T08:00:00.000Z',
    id: 'assignment-n',
    plannedMemberName: '赵医生',
    plannedMembershipId: 'member-night',
    schedulePeriodId: 'period-c',
    scheduleRoleId: 'role-a',
    scheduleRoleName: '一线',
    shiftTypeAbbreviation: 'N',
    shiftTypeColor: '#EEE8FF',
    shiftTypeId: 'shift-n',
    shiftTypeName: '凌晨班',
    shiftTypeTextColor: '#4A2A8A',
    slotPosition: 2,
    startsAt: '2026-08-01T16:00:00.000Z',
  },
  {
    businessDate: '2026-09-20',
    changeMarkers: [],
    endsAt: '2026-09-20T08:00:00.000Z',
    id: 'assignment-september-late',
    plannedMemberName: '周医生',
    plannedMembershipId: 'member-september-late',
    schedulePeriodId: 'period-september',
    scheduleRoleId: 'role-a',
    scheduleRoleName: '一线',
    shiftTypeAbbreviation: 'A',
    shiftTypeColor: '#DCEEFF',
    shiftTypeId: 'shift-a',
    shiftTypeName: '白班',
    shiftTypeTextColor: '#084FA6',
    slotPosition: 1,
    startsAt: '2026-09-20T00:00:00.000Z',
  },
  {
    businessDate: '2026-09-03',
    changeMarkers: ['overtime'],
    endsAt: '2026-09-03T08:00:00.000Z',
    id: 'assignment-september-early',
    plannedMemberName: '陈医生',
    plannedMembershipId: 'member-planned',
    schedulePeriodId: 'period-september',
    scheduleRoleId: 'role-a',
    scheduleRoleName: '一线',
    shiftTypeAbbreviation: 'A',
    shiftTypeColor: '#DCEEFF',
    shiftTypeId: 'shift-a',
    shiftTypeName: '白班',
    shiftTypeTextColor: '#084FA6',
    slotPosition: 1,
    startsAt: '2026-09-03T00:00:00.000Z',
  },
] as const;

export const calendarGoldenHolidays: readonly (readonly [string, CalendarGoldenHoliday])[] = [
  ['2026-10-01', { date: '2026-10-01', holidayName: '国庆节', isOffDay: true, isWorkday: false }],
  ['2026-10-02', { date: '2026-10-02', holidayName: '国庆节', isOffDay: true, isWorkday: false }],
  ['2026-10-03', { date: '2026-10-03', holidayName: '国庆节', isOffDay: true, isWorkday: false }],
  ['2026-10-10', { date: '2026-10-10', holidayName: '国庆节', isOffDay: false, isWorkday: true }],
  ['2026-10-15', { date: '2026-10-15', holidayName: '院庆日', isOffDay: true, isWorkday: false }],
];
